In [1]:
import numpy as np
import pandas  as pd
import matplotlib.pyplot as plt
from scipy import stats as s

In [2]:
data = pd.read_csv("data.csv")

In [5]:
data.shape


(569, 33)

In [7]:
data.drop(columns = ["id" , "Unnamed: 32"] ,inplace = True)

In [8]:
data[data["diagnosis"] == "B"].shape

(357, 31)

In [9]:
data[data["diagnosis"] == "M"].shape

(212, 31)

In [10]:
training_data_Len = int(0.7 * data.shape[0])
training_data_Len

398

In [11]:
B_training_data = data[data["diagnosis"] == 'B'].iloc[0:training_data_Len//2]

M_training_data = data[data["diagnosis"] == "M"].iloc[0:training_data_Len//2]

In [14]:
M_training_data.shape

(199, 31)

In [13]:
training_data =  pd.concat([B_training_data,M_training_data] ,axis = 0)

In [15]:
training_data.shape

(398, 31)

In [17]:
cv_data_len = int(0.2 * data.shape[0])
cv_data_len

113

In [18]:
B_remaining_data = data[data["diagnosis"] == "B"].iloc[training_data_Len//2 : ]
    
M_reamaining_data = data[data["diagnosis"] == "M"].iloc[training_data_Len//2 :]    

In [19]:
B_remaining_data.shape

(158, 31)

In [20]:
M_reamaining_data.shape

(13, 31)

In [21]:
remaining_data = pd.concat([B_remaining_data,M_reamaining_data])

In [22]:
remaining_data.shape

(171, 31)

In [24]:
mu_hat_b = np.array(training_data[training_data["diagnosis"] == 'B'].iloc[:,1:].mean())
mu_hat_b

array([1.19843970e+01, 1.71109045e+01, 7.69514070e+01, 4.50212563e+02,
       9.28012563e-02, 7.74771859e-02, 4.57767472e-02, 2.50231407e-02,
       1.75215075e-01, 6.29455276e-02, 2.91945729e-01, 1.21130854e+00,
       2.01376985e+00, 2.14023668e+01, 7.34034673e-03, 2.14668643e-02,
       2.68529432e-02, 1.00206181e-02, 2.18462261e-02, 3.74105678e-03,
       1.31722864e+01, 2.23857286e+01, 8.53800000e+01, 5.41368844e+02,
       1.24279497e-01, 1.71125829e-01, 1.57116915e-01, 7.08428191e-02,
       2.71169849e-01, 7.85500503e-02])

In [26]:
sigma_hat_b = np.array(training_data[training_data["diagnosis"] == 'B'].iloc[:,1:].cov())
sigma_hat_b.shape

(30, 30)

In [31]:
np.linalg.det(sigma_hat_b)

1.3582567523082033e-76

In [32]:
sigma_hat_b.()

array([2.94091972e+00, 1.13288547e+01, 1.28577764e+02, 1.60340024e+04,
       1.59580656e-04, 1.12158981e-03, 2.48804537e-03, 2.68474522e-04,
       6.84821186e-04, 4.54429147e-05, 1.38731442e-02, 3.36939014e-01,
       6.15979077e-01, 8.64088828e+01, 9.71364606e-06, 3.30205927e-04,
       1.58704044e-03, 4.00534040e-05, 6.08239742e-05, 1.18392359e-05,
       3.72826867e+00, 2.38599408e+01, 1.73844674e+02, 2.42578726e+04,
       3.79521510e-04, 8.60889580e-03, 2.40571051e-02, 1.31268101e-03,
       1.98506737e-03, 1.87929964e-04])

In [33]:
np.linalg.matrix_rank(sigma_hat_b)

30

In [ ]:
np.linalg. 

In [27]:
mu_hat_m = np.array(training_data[training_data["diagnosis"] == 'M'].iloc[1:].mean())
mu_hat_m

array([1.73531818e+01, 2.15177273e+01, 1.14577424e+02, 9.66879293e+02,
       1.02851616e-01, 1.43931010e-01, 1.57924091e-01, 8.66106061e-02,
       1.92612626e-01, 6.26596465e-02, 6.03631313e-01, 1.20564091e+00,
       4.27560606e+00, 7.17526263e+01, 6.84155556e-03, 3.22116010e-02,
       4.14066162e-02, 1.49975101e-02, 2.06213081e-02, 4.06116162e-03,
       2.10283838e+01, 2.92647475e+01, 1.40439444e+02, 1.40978990e+03,
       1.45464091e-01, 3.73496010e-01, 4.45720606e-01, 1.81332374e-01,
       3.24817677e-01, 9.16505051e-02])

In [30]:
sigma_hat_m = np.array(training_data[training_data["diagnosis"] == 'M'].iloc[:,1:].cov() )
sigma_hat_m.shape

(30, 30)

In [ ]:
def multivarate_prob(data):
    
    inputs = np.array(data.iloc[:,1:3])
    
    posterior_m = s.multivariate_normal.pdf(inputs,mu_hat_m,sigma_hat_m) * M_prior
    
    posterior_b  = s.multivariate_normal.pdf(inputs,mu_hat_b,sigma_hat_b) *B_prior
    
    boolen_mask = posterior_b > posterior_m
    
    predicted_cat = pd.Series(boolen_mask)
    
    predicted_cat.replace(to_replace=[False,True] ,value=["M" ,"B"],inplace= True)
    
    return np.array(predicted_cat)